# This one seems to work when I use it in the UI.
#
# Basic definition.
# DyDB works with the existing Lambdas. So, that's done.
#
# TODO: values. Requires me to somehow invoke an initalisation script.
# TODO: incorporate the Lambdas.

AWSTemplateFormatVersion: 2010-09-09
Description: An attempt to specify the Home-Assistant-Watchdog stack. Having a lot of trouble. Work in progress.

Resources:
  HeatbeatDatabaseAllAccessRole:
    Type:  AWS::IAM::Role
    Properties:
      RoleName: HeatbeatDatabaseAllAccess
      Description: Allows Lambda functions to call AWS services on your behalf.
      Path: /
      # Unsure what this does?
      # https://devops.stackexchange.com/questions/5094/what-is-the-purpose-of-assumerolepolicydocument-in-iam/5099
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: 
            - lambda.amazonaws.com
          Action: 
          - sts:AssumeRole
      # This next param links the AWS-managed policy to the role.
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  HomeAssistantHeartBeatDyDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: HomeAssistantHeartBeat
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
