# This one seems to work when I use it in the UI.
#
# Basic definition.
# DyDB works with the existing Lambdas. So, that's done.
#
# TODO: values. Requires me to somehow invoke an initalisation script.
# TODO: incorporate the Lambdas.

AWSTemplateFormatVersion: 2010-09-09
Description: An attempt to specify the Home-Assistant-Watchdog stack. Having a lot of trouble. Work in progress.

Resources:
  HomeAssistantHeartBeat:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: HomeAssistantHeartBeat
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
