version: 0.0
environment_variables:
  plaintext:
    "INPUT_FILE": "Template.yaml"
    "S3_BUCKET": ""
containers:
  LambdaFunctions:
    phases:
      during_build:
        commands:
          - pip install --upgrade pip awscli
          - aws cloudformation package --s3-bucket $S3_BUCKET --template-file template.yaml --output-template-file output-template.yaml

    artifacts:
      files:
        - post-saml.yaml
        - beta.json 