version: 0.2 # Turns out this matters - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-versions
environment_variables:
  plaintext:
    "INPUT_FILE": "api/Template.yml"
    "S3_BUCKET": "codepipeline-ap-southeast-2-9165-8911-9438-artifactstore"

# Phase definitions: https://aws.amazon.com/blogs/apn/an-introduction-to-aws-codebuild/

phases:
  install:
    runtime-versions:
      python: 3.9
#  pre_build:
#    commands:
#      - pip install --upgrade pip
#      - pip install --user aws-sam-cli
  build:
    commands:
#      - sam build --template-file api/Template.yml
#      - sam package --template-file $INPUT_FILE --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
#      - aws cloudformation package --s3-bucket $S3_BUCKET --template-file $INPUT_FILE --output-template-file output-template.yaml


#      - sam build --template-file $INPUT_FILE
      - sam package --template-file template.yaml --s3-bucket codepipeline-ap-southeast-2-9165-8911-9438-artifactstore --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
