version: 0.2 # Turns out this matters - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-versions
environment_variables:
  plaintext:
    "INPUT_FILE": "Template.yml"
    "S3_BUCKET": "codepipeline-ap-southeast-2-9165-8911-9438-artifactstore"

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws cloudformation package --s3-bucket $S3_BUCKET --template-file template.yml --output-template-file output-template.yaml

artifacts:
  files:
    - post-saml.yaml
    - beta.json 
