AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  # DynamoDB
  HomeAssistantHeartBeatDyDB:
    Type: AWS::Serverless::SimpleTable
    Properties: 
      PrimaryKey:
        Name: ID
        Type: String
      TableName: HomeAssistantHeartBeat

  # Lambdas
  onHeartbeatFromHomeAssistant:
    Type: AWS::Serverless::Function
    DependsOn: HeatbeatDatabaseAllAccessRole
    Properties:
      Handler: onHeartbeatFromHomeAssistant.lambda_handler
      CodeUri: . 
      Description: 'The hearbeat handler function'
      MemorySize: 256
      Timeout: 5
      Role: !GetAtt HeatbeatDatabaseAllAccessRole.Arn
      Runtime: python3.9
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /heartbeat
            Method: get

  onCheckHeartbeatRecency:
    Type: AWS::Serverless::Function
    DependsOn: HeatbeatDatabaseAllAccessRole
    Properties:
      Handler: onCheckHeatbeatRecency.lambda_handler
      CodeUri: . 
      Description: 'The hearbeat recency checkerer handler function'
      MemorySize: 256
      Timeout: 5
      Role: !GetAtt HeatbeatDatabaseAllAccessRole.Arn
      Runtime: python3.9

  # Roles
  HeatbeatDatabaseAllAccessRole:
    Type:  AWS::IAM::Role
    Properties:
      RoleName: HeatbeatDatabaseAllAccess
      Description: Allows Lambda functions to call AWS services on your behalf.
      Path: /
      # Unsure what this does?
      # https://devops.stackexchange.com/questions/5094/what-is-the-purpose-of-assumerolepolicydocument-in-iam/5099
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SNSRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:*'
                Resource: '*'
  
  # SNS
  HeartbeatNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: false
      Subscription:
        - Endpoint: "+61457805418"
          Protocol: "sms"






