Transform: 'AWS::Serverless-2016-10-31'
Parameters: 
  TopicNameParameter: 
    Type: String
Resources:
  myFirstHandlerPython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: onHeartbeatFromHomeAssistant.lambda_handler
      CodeUri: ./
      Description: 'The hearbeat handler function'
      MemorySize: 256
      Timeout: 5

      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /sam
            Method: get



#      Policies:
#        - SNSPublishMessagePolicy:
#            TopicName: !Ref TopicNameParameter


#Resources:
#  HearbeatFromHomeAssistant:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: /
#      Handler: onHeartbeatFromHomeAssistant.lambda_handler
#      Runtime: python3.9
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /heartbeatFromHomeAssistant
#            Method: get





